version: '3'

services:

  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: '$DB_USER'
      POSTGRES_DB: '$DB_NAME'
      POSTGRES_PASSWORD: '$DB_PASSWORD'
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    command: >
      bash -c "poetry run python3 manage.py migrate && poetry run python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
    environment:
      PYTHONPATH: /code

volumes:
  pg_data: